;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dired-next-line
        indent-for-tab-command
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-buffer-menu
        ))
